In [1]:
import sys

print(sys.executable)

c:\Users\gamma\AppData\Local\Programs\Python\Python310\python.exe


In [290]:
import pandas as pd

data = pd.read_csv('https://raw.githubusercontent.com/4GeeksAcademy/naive-bayes-project-tutorial/main/playstore_reviews.csv')

In [291]:
data.head()

package_name                                             review  \
0  com.facebook.katana   privacy at least put some option appear offli...   
1  com.facebook.katana   messenger issues ever since the last update, ...   
2  com.facebook.katana   profile any time my wife or anybody has more ...   
3  com.facebook.katana   the new features suck for those of us who don...   
4  com.facebook.katana   forced reload on uploading pic on replying co...   

   polarity  
0         0  
1         0  
2         0  
3         0  
4         0

In [292]:
def limpiar_tabla(datos):
    datos = datos.drop('package_name', axis=1)
    datos['review'] = datos['review'].str.strip().str.lower()

    return datos

data = limpiar_tabla(data)

data

review  polarity
0    privacy at least put some option appear offlin...         0
1    messenger issues ever since the last update, i...         0
2    profile any time my wife or anybody has more t...         0
3    the new features suck for those of us who don'...         0
4    forced reload on uploading pic on replying com...         0
..                                                 ...       ...
886  loved it i loooooooooooooovvved it because it ...         1
887  all time legendary game the birthday party lev...         1
888  ads are way to heavy listen to the bad reviews...         0
889  fun works perfectly well. ads aren't as annoyi...         1
890  they're everywhere i see angry birds everywher...         1

[891 rows x 2 columns]

In [293]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data['review'], data['polarity'], train_size=0.2, random_state=42)


In [294]:
# Asignar X a columna Review e Y a polarity
X = data["review"]
y = data["polarity"]

# Dividir dataset en train y test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [295]:
from sklearn.feature_extraction.text import CountVectorizer

contador = CountVectorizer(token_pattern=r'\b\w{3,}\b')

X_vectorizada = contador.fit_transform(X_train).toarray()

X_test_vectorizada = contador.transform(X_test).toarray()

In [310]:
for palabra in contador.get_feature_names_out():
    if len(palabra) <= 3:
        print(palabra)
        #Ahora no salen palabras menores a 3

000
100
101
125
1st
200
2gb
2nd
367
3rd
500
505
6mb
826
aap
act
add
ads
age
ago
ain
air
all
and
any
api
apk
app
aps
are
ask
atm
bad
bar
big
bit
boo
box
boy
bro
btw
bug
but
buy
bye
can
cap
clr
cnt
coc
con
coz
cpu
cue
cut
cuz
dat
day
dbl
dev
did
die
dis
dog
don
dps
dud
due
ear
eat
els
end
eng
erm
err
esp
etc
eye
fab
fan
far
fav
fee
few
fit
fix
fly
for
frm
fun
gem
get
gif
gig
god
got
grr
gud
guy
had
hai
han
has
hau
hey
him
his
hit
hog
hot
how
htc
iam
ice
idk
ill
ily
ing
ios
ish
isn
its
itâ
ive
jam
job
jot
key
kid
kmg
knw
lag
lai
lee
let
lil
log
lol
lot
low
lte
lvl
mad
man
map
max
may
mea
med
meh
men
mic
mid
mms
mom
mp3
msg
nag
nai
net
new
non
noo
nor
not
now
nut
nyc
off
old
one
ony
opt
our
out
own
pad
pan
pay
pcs
pdf
per
phn
pic
pig
pls
plz
pop
ppl
pre
put
que
ram
ran
red
rid
rio
rip
run
sad
saw
say
sec
see
set
sgh
she
shw
sim
sir
sis
sit
smh
sms
som
sor
sos
sso
std
sum
sun
sux
t10
tab
tag
tap
tat
ten
tge
th9
tha
the
thi
thn
tho
ths
tht
tip
tnx
ton
too
top
tos
try
two
ugh
umm
ups
url
use


In [297]:
contador.get_feature_names_out()

array(['000', '100', '101', ..., 'ťŕľ', 'żŕľ', 'žŕľ'], dtype=object)

In [298]:
X_vectorizada

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [299]:
X_test_vectorizada

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [300]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_vectorizada, y_train)

MultinomialNB()

In [301]:
y_predicha = model.predict(X_test_vectorizada)

y_predicha

array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0], dtype=int64)

In [302]:
from sklearn.metrics import accuracy_score, classification_report

accuracy_score(y_predicha,y_test)

0.8547486033519553

In [303]:
from sklearn.naive_bayes import GaussianNB, BernoulliNB

for modelo_prueba in [GaussianNB(), BernoulliNB()]:
    modelo_prueba.fit(X_vectorizada, y_train)
    y_pred_aux = modelo_prueba.predict(X_test_vectorizada)
    print(f"{modelo_prueba} con una precision de: {accuracy_score(y_test, y_pred_aux)}")

GaussianNB() con una precision de: 0.8100558659217877
BernoulliNB() con una precision de: 0.8547486033519553


In [304]:
import numpy as np
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV

hyperparams = {
    "alpha": np.linspace(0.01, 10.0, 200),
    "fit_prior": [True, False]
}

random_search = RandomizedSearchCV(model, hyperparams, n_iter = 50, scoring = "accuracy", cv = 5, random_state = 42)
print(random_search)

RandomizedSearchCV(cv=5, estimator=MultinomialNB(), n_iter=50,
                   param_distributions={'alpha': array([ 0.01      ,  0.06020101,  0.11040201,  0.16060302,  0.21080402,
        0.26100503,  0.31120603,  0.36140704,  0.41160804,  0.46180905,
        0.51201005,  0.56221106,  0.61241206,  0.66261307,  0.71281407,
        0.76301508,  0.81321608,  0.86341709,  0.91361809,  0.9638191 ,
        1.0140201 ,  1.06422111,  1.11442211,  1.1646231...
        8.54417085,  8.59437186,  8.64457286,  8.69477387,  8.74497487,
        8.79517588,  8.84537688,  8.89557789,  8.94577889,  8.9959799 ,
        9.0461809 ,  9.09638191,  9.14658291,  9.19678392,  9.24698492,
        9.29718593,  9.34738693,  9.39758794,  9.44778894,  9.49798995,
        9.54819095,  9.59839196,  9.64859296,  9.69879397,  9.74899497,
        9.79919598,  9.84939698,  9.89959799,  9.94979899, 10.        ]),
                                        'fit_prior': [True, False]},
                   random_state=42, s

In [305]:
hyperparams = {
    "alpha": np.linspace(0.01, 10.0, 200),
    "fit_prior": [True, False]
}

random_search = RandomizedSearchCV(model, hyperparams, n_iter = 50, scoring = "accuracy", cv = 5, random_state = 42)
print(random_search)

RandomizedSearchCV(cv=5, estimator=MultinomialNB(), n_iter=50,
                   param_distributions={'alpha': array([ 0.01      ,  0.06020101,  0.11040201,  0.16060302,  0.21080402,
        0.26100503,  0.31120603,  0.36140704,  0.41160804,  0.46180905,
        0.51201005,  0.56221106,  0.61241206,  0.66261307,  0.71281407,
        0.76301508,  0.81321608,  0.86341709,  0.91361809,  0.9638191 ,
        1.0140201 ,  1.06422111,  1.11442211,  1.1646231...
        8.54417085,  8.59437186,  8.64457286,  8.69477387,  8.74497487,
        8.79517588,  8.84537688,  8.89557789,  8.94577889,  8.9959799 ,
        9.0461809 ,  9.09638191,  9.14658291,  9.19678392,  9.24698492,
        9.29718593,  9.34738693,  9.39758794,  9.44778894,  9.49798995,
        9.54819095,  9.59839196,  9.64859296,  9.69879397,  9.74899497,
        9.79919598,  9.84939698,  9.89959799,  9.94979899, 10.        ]),
                                        'fit_prior': [True, False]},
                   random_state=42, s

In [306]:
random_search.fit(X_vectorizada, y_train)

mejores_parametros = random_search.best_estimator_

mejores_parametros

MultinomialNB(alpha=1.0642211055276383)

In [307]:
mejor_modelo = random_search.best_estimator_
#mejor_modelo.fit(X_vectorizada, y_train)
y_pred = mejor_modelo.predict(X_test_vectorizada)
y_pred

accuracy_score(y_test,y_pred)



0.8547486033519553

In [308]:
from pickle import dump

dump(model, open("../workflows", "wb"))

In [309]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.95      0.90       126
           1       0.85      0.62      0.72        53

    accuracy                           0.85       179
   macro avg       0.85      0.79      0.81       179
weighted avg       0.85      0.85      0.85       179

